//
//  PDF.Document Snapshot Tests.swift
//  swift-pdf-standard
//

import Testing
import Tests_Inline_Snapshot
import PDF_Standard_Test_Support

extension PDF.Document {
    @Suite
    struct Test {
        @Suite struct Snapshot {}
    }
}

// MARK: - Snapshot

extension PDF.Document.Test.Snapshot {
    @Test
    func `simple document`() {
        let document = PDF.Document(
            info: PDF.Document.Info(
                title: "Simple Test",
                creator: "swift-pdf-standard tests"
            ),
            pages: [
                PDF.Page(
                    mediaBox: .letter,
                    content: PDF.ContentStream { builder in
                        builder.beginText()
                        builder.setFont(PDF.Font.helvetica, size: 24)
                        builder.moveText(dx: 72, dy: 700)
                        builder.showText("PDF Standard Snapshot Test")

                        builder.setFont(PDF.Font.helvetica, size: 12)
                        builder.moveText(dx: 0, dy: -30)
                        builder.showText("This PDF was generated by swift-pdf-standard snapshot tests.")
                        builder.endText()
                    },
                    resources: PDF.Resources(fonts: [
                        PDF.Font.helvetica.resourceName: PDF.Font.helvetica
                    ])
                )
            ]
        )

        snapshot(as: .pdf, named: "simple-document") { document }
    }

    @Test
    func `multi-page document`() {
        func page(_ title: Swift.String, _ body: Swift.String) -> PDF.Page {
            PDF.Page(
                mediaBox: .a4,
                content: PDF.ContentStream { builder in
                    builder.beginText()
                    builder.setFont(PDF.Font.Helvetica.bold, size: 18)
                    builder.moveText(dx: 72, dy: 750)
                    builder.showText(title)

                    builder.setFont(PDF.Font.helvetica, size: 12)
                    builder.moveText(dx: 0, dy: -30)
                    builder.showText(body)
                    builder.endText()
                },
                resources: PDF.Resources(fonts: [
                    PDF.Font.helvetica.resourceName: PDF.Font.helvetica,
                    PDF.Font.Helvetica.bold.resourceName: PDF.Font.Helvetica.bold,
                ])
            )
        }

        let document = PDF.Document(
            info: PDF.Document.Info(
                title: "Multi-Page Test",
                creator: "swift-pdf-standard tests"
            ),
            pages: [
                page("Page 1", "First page content."),
                page("Page 2", "Second page content."),
                page("Page 3", "Third page content."),
            ]
        )

        snapshot(as: .pdf, named: "multi-page-document") { document }
    }

    @Test
    func `standard 14 fonts`() {
        var contentBuilder = PDF.ContentStream.Builder()
        contentBuilder.beginText()

        var dy: PDF.UserSpace.Dy = 700
        var fonts: [PDF.COS.Name: PDF.Font] = [:]

        for pdfFont in PDF.Font.standard14 {
            fonts[pdfFont.resourceName] = pdfFont
            contentBuilder.setFont(pdfFont, size: 14)
            contentBuilder.moveText(dx: 72, dy: dy)
            contentBuilder.showText(
                "\(pdfFont.baseFontName.rawValue): The quick brown fox jumps over the lazy dog."
            )
            dy = -30
            contentBuilder.moveText(dx: -72, dy: 0)
        }

        contentBuilder.endText()

        let document = PDF.Document(
            info: PDF.Document.Info(title: "Standard 14 Fonts"),
            pages: [
                PDF.Page(
                    mediaBox: .letter,
                    content: PDF.ContentStream(data: contentBuilder.data),
                    resources: PDF.Resources(fonts: fonts)
                )
            ]
        )

        snapshot(as: .pdf, named: "standard-14-fonts") { document }
    }
}
